#!/usr/bin/env python3
"""Assemble two single-file documents from the manuscript section drafts:
  manuscript/full_manuscript.md  — the paper (abstract→intro→results→discussion→methods→legends→tables→refs)
  manuscript/thesis_chapter.md   — thesis version with expanded intro/methods/discussion (no length limit)
Section drafts in manuscript/*.md are the source of truth; thesis expansions live in
manuscript/_thesis_{intro,methods_appendix,discussion_extra}.md. Re-run after editing any of them."""
import re, os
os.chdir(os.path.join(os.path.dirname(__file__), ".."))
def read(f): return open(f).read()
def shift(t, n=1): return re.sub(r'^(#{1,5}) ', lambda m: '#'*(len(m.group(1))+n)+' ', t, flags=re.M)
def body(f): return re.sub(r'^# .*\n', '', read(f), count=1)

def abstract():
    ab = read("manuscript/abstract.md").split("### Author-facing notes")[0]
    return re.search(r'## Abstract\s*\n(.*)', ab, re.S).group(1).strip()

def results():
    text = re.sub(r'(?s)^\s*> .*?\n\n', '', body("manuscript/results.md"), count=1).strip()
    # The assembler owns this section heading; modular Results begins at its first subsection.
    return re.sub(r'^##\s+Results\s*\n+', '', text, flags=re.I).strip()

def figure_legends():
    fl = read("manuscript/figures.md"); fl = fl[fl.find("## Main figures"):]
    fl = re.sub(r'Sources?:.*?(?=\n\n|\Z)', '', fl, flags=re.S)
    fl = re.sub(r'`figures/[^`]+`', '', fl)
    fl = re.sub(r'\(generated by[^)]*\)', '', fl)
    fl = re.sub(r';?\s*docs?:.*', '', fl)
    for p in ('scripts', 'results', 'data'):
        fl = re.sub(r'`%s/[^`]+`' % p, '', fl)
    fl = re.sub(r'`\.\./[^`]+`', '', fl)
    # Remove orphan punctuation left behind when source paths are stripped.
    fl = re.sub(r'\*\*\s*:\s*', '** ', fl)
    fl = re.sub(r'\(A\)\s*;\s*', '(A) ', fl)
    fl = re.sub(r'\(B\)\s*;\s*', '(B) ', fl)
    fl = re.sub(r'\*\*\s*;\s*', '** ', fl)
    fl = re.sub(r'\s{2,}', ' ', fl)
    fl = re.sub(r'(\*\*Figure[^\n]*?\*\*)\s*\.\s*', r'\1 ', fl)
    fl = re.sub(r'\n[ \t]*\.\s*\n', '\n\n', fl)
    fl = re.sub(r'[ \t]+\n', '\n', fl); fl = re.sub(r'\n{3,}', '\n\n', fl)
    return fl.strip()

TABLES = lambda: body("manuscript/tables.md").strip()
REFS   = lambda: read("manuscript/references.md").strip()

# ---------- full manuscript ----------
TITLE_M = ("# Strain2bScan: strain-level profiling from 2bRAD markers across microbiomes\n\n"
"[Author 1 Given Name Surname]<sup>1</sup>, [Author 2 Given Name Surname]<sup>2</sup>, "
"[additional authors to be completed]\n\n"
"<sup>1</sup> [Department, Institution, City, Country]; "
"<sup>2</sup> [Department, Institution, City, Country].\n"
"[Add further numbered affiliations and mark the corresponding author here.]\n\n"
"*Author-facing placeholder: replace all bracketed author and affiliation fields before submission.*\n\n---")
full = "\n\n".join([
    TITLE_M,
    "## Abstract\n\n" + abstract(),
    "## Introduction\n\n" + body("manuscript/introduction.md").strip(),
    "## Results\n\n" + shift(results(), 1),
    "## Discussion\n\n" + body("manuscript/discussion.md").strip(),
    "## Methods\n\n" + shift(body("manuscript/methods.md").strip(), 1),
    "## Funding\n\n"
    "[Funding statement to be completed. List funder names, award numbers and recipient initials, or state "
    "\u201cThis work received no external funding.\u201d Do not leave this placeholder in a submitted version.]\n\n"
    "## Data and code availability\n\n"
    "The Strain2bScan source code is available at https://github.com/HuangShiLab/Strain2bScan. "
    "Derived tables, benchmark configurations, checksums and assembly scripts are available at "
    "https://github.com/HuangShiLab/Strain2bScan-paper. Public human metagenome reads used in the "
    "exploratory analyses are from PRJNA1131785, PRJNA288562, PRJNA1517970, PRJNA1191223 and PRJNA1191225. "
    "Commercial ATCC mock standards are identified by their catalogue names in the manuscript. No new "
    "human subject data were generated for this study.\n\n"
    "## Figure legends\n\n" + shift(figure_legends(), 1),
    "## Tables\n\n" + TABLES(),
    REFS(),
]) + "\n"
open("manuscript/full_manuscript.md", "w").write(full)

# ---------- thesis chapter ----------
disc = body("manuscript/discussion.md").strip()
extra = read("manuscript/_thesis_discussion_extra.md").strip()
i = disc.find("**Conclusion.**")
disc_full = disc[:i].rstrip() + "\n\n" + extra + "\n\n" + disc[i:]
methods_full = (shift(body("manuscript/methods.md").strip(), 1)
    + "\n\n### Extended algorithmic detail, data structures and complexity\n\n"
    + shift(read("manuscript/_thesis_methods_appendix.md").strip(), 1))
TITLE_T = ("# Strain2bScan: strain-level profiling from 2bRAD markers across microbiomes\n\n"
"*Thesis chapter. Extended background, technical methods and discussion relative to the manuscript "
"version (`full_manuscript.md`).*\n\n---")
thesis = "\n\n".join([
    TITLE_T,
    "## Summary\n\n" + abstract(),
    "## 1. Introduction\n\n" + shift(read("manuscript/_thesis_intro.md").strip(), 1),
    "## 2. Results\n\n" + shift(results(), 1),
    "## 3. Discussion\n\n" + disc_full,
    "## 4. Methods\n\n" + methods_full,
    "## 5. Figure legends\n\n" + shift(figure_legends(), 1),
    "## 6. Tables\n\n" + TABLES(),
    REFS().replace("## References", "## 7. References"),
]) + "\n"
open("manuscript/thesis_chapter.md", "w").write(thesis)

print("wrote manuscript/full_manuscript.md  (%d words)" % len(full.split()))
print("wrote manuscript/thesis_chapter.md   (%d words)" % len(thesis.split()))
